apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
  image: nginx:alpine
  ports:
  - containerPort: 80
  livenessProbe:
    httpGet:
      path: /index.html
      port: 80
    inititalDelaySeconds: 15
    timeoutSeconds: 2 #Deafult is 1
    periodSeconds: 5 #Deafult is 10
    failureThreshold: 1 #Deafult is 3
  readinessProbe:
    httpGet:
      path: /index.html
      port: 80
    inititalDelaySeconds: 2
    periodSeconds: 5